name: addition
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: | 
          npm install python
          python -c "print(\"Hello python"\)"
        
